services:
  - type: web
    name: mapup-backend
    runtime: docker
    rootDirectory: ./backend
    dockerfilePath: ./Dockerfile
    repo: https://github.com/deadheaven07/Assignment_MapUp_
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: mapup-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: mapup-postgres
          property: port
      - key: DB_USER
        fromDatabase:
          name: mapup-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mapup-postgres
          property: password
      - key: DB_NAME
        fromDatabase:
          name: mapup-postgres
          property: database

databases:
  - name: mapup-postgres
    plan: free